const RESERVED = new Set(["accounts", "about", "explore", "direct", "p", "reel", "reels", "stories", "legal", "privacy", "developer", "developers", "web", "challenge", "emails", "settings", "push", "download", "directory"]);
export function normalizeUsername(value) {
  const username = String(value).trim().replace(/^@/, "").toLowerCase();
  return /^[a-z0-9._]{1,30}$/.test(username) && !RESERVED.has(username) ? username : null;
}
export function usernameFromUrl(href) {
  try {
    const url = new URL(href);
    if (url.protocol !== "https:" || !["instagram.com", "www.instagram.com"].includes(url.hostname) || url.username || url.password || url.port) return null;
    const parts = url.pathname.split("/").filter(Boolean);
    const candidate = parts.length === 1 ? parts[0] : parts.length === 2 && parts[0] === "_u" ? parts[1] : null;
    return candidate ? normalizeUsername(decodeURIComponent(candidate)) : null;
  } catch { return null; }
}
export function parseExport(html, document) {
  // Template contents stay inert: never attach imported HTML to the live document.
  const template = document.createElement("template");
  template.innerHTML = html;
  const usernames = [...new Set([...template.content.querySelectorAll("a[href]")]
    .map(a => usernameFromUrl(a.getAttribute("href"))).filter(Boolean))].sort();
  const owners = [...new Set([...template.content.querySelectorAll('aside')]
    .map(el => normalizeUsername(el.textContent.match(/Generated by\s+([^\s]+)\s+on\b/i)?.[1] || "")).filter(Boolean))];
  return { usernames, owners };
}
export function mergeRows(rows, usernames) {
  const existing = new Set(rows.map(row => row.username));
  return [...rows, ...usernames.filter(u => !existing.has(u)).map(username => ({username, selected: true, status: "pending", detail: ""}))];
}
export function nextRow(rows) { return rows.find(row => row.selected && row.status === "pending"); }
export function recoverRows(rows) {
  return rows.map(row => row.status === "blocking" ? {...row, status: "failed", detail: "Interrupted. Check this profile before retrying."} : row);
}
export function counts(rows) {
  return { total: rows.length, pending: rows.filter(r => r.selected && r.status === "pending").length,
    done: rows.filter(r => ["blocked", "already-blocked"].includes(r.status)).length,
    failed: rows.filter(r => r.status === "failed").length };
}

export function startBlockReason({ready, running, verifying, verified, confirmed, pending, interval}) {
  if (!ready) return "Dashboard is not ready. Close other Fresh Start tabs and reopen this dashboard.";
  if (running) return "A run is already in progress.";
  if (verifying) return "Wait for account verification to finish.";
  if (!verified) return "Verify your new account before starting.";
  if (!Number.isInteger(interval) || interval < 10 || interval > 600) return "Set Seconds between profiles to a whole number from 10 to 600. The default is 30.";
  if (!pending) return "No selected pending accounts. Select accounts in the list; interrupted profiles need review before retrying.";
  if (!confirmed) return "Check the confirmation box after reviewing your selected accounts.";
  return "";
}
